= Appsody - Create a Stack
:toc:

== Prerequisites

include::common/prerequisites.adoc[]

== Getting Started

First we need to clone the stacks repository provided by appsody.

----
git clone https://github.com/appsody/stacks.git
cd stacks
----

The stacks repository provides us with all the stacks provided by Appsody as well as a sample stack in the `/samples/sample-stack` directory.  The `sample stack` directory gives us the basic skeleton for starting a stack from scratch.

== Modifiying a Stack's Template Code

For this walkthrough however we are going to modify one of the existing stacks templates.  In this case we are going to modify the `nodejs-express` stack's `simple` template.  We are going to modify the `app.js` and the `README.md` files.

Let's start by navigating to the `nodejs-express simple template` directory.

----
cd incubator/nodejs-express/templates/simple
----

Now we can copy the simple template into a new directory, to create a new template.

----
cp 
----

== Building and Testing the Stack
