= Tekton - Configure GitHub Credentials
:toc:
:imagesdir: images

== Prerequisites

* https://cloud.ibm.com/kubernetes/catalog/openshiftcluster[Openshift Cluster]
** https://www.ibm.com/support/knowledgecenter/en/SSCSJL/install-icpa-cli.html[Kabenero Enterprise (Installed with IBM Cloud Pak for Applications)]
*** Tekton Operator and TekTon Dashboard
*** Knative Operator
* The following command line (CLI) tools and configured:
** https://git-scm.com/book/en/v2/Getting-Started-Installing-Git[git]
** https://www.okd.io/download.html[oc]

== Getting Started

When using Tekton, building a pipeline will require code to be pulled from either a public or private repository. For security reasons an access token will need to be generated and configured on Tekton in order for it to pull any code from the repository.  In this guide we will create and configure s github token for a tekton pipeline to gain access to the repository to pull code.

== Generating the Token

First thing we need to do is generate the Github token.  Open Github.com and login with your username and password.