= SpringBoot - Appsody sample application
Hemankita Perabathini <Hemankita.Perabathini@ibm.com>
v1.0, 2019-09-17
:toc:
:imagesdir: images

== Prerequisites

* https://cloud.ibm.com/kubernetes/catalog/openshiftcluster[Openshift] (We are using the IKS Openshift cluster)
* Docker for Desktop - https://docs.docker.com/docker-for-mac/install/[Mac], https://docs.docker.com/docker-for-windows/install/[Windows]
* The following command line (CLI) tools and configured:
  ** docker - It comes with the Docker for Desktop installation.
  ** https://www.okd.io/download.html[oc]
  ** https://git-scm.com/book/en/v2/Getting-Started-Installing-Git[git]
  ** https://appsody.dev/docs/getting-started/installation[appsody]

== Add Kabanero Collection to appsody

- From the Cloud Pak for Applications landing page get the `Collection Hub` URL. For example in our example it is as follows.

`https://github.com/kabanero-io/collections/releases/download/v0.1.2/kabanero-index.yaml`

- Use the appsody CLI to add the Collection repo.

[source, bash]
----
appsody repo add kabanero https://github.com/kabanero-io/collections/releases/download/v0.1.2/kabanero-index.yaml
----

- Set the repo as default.

[source, bash]
----
appsody repo set-default kabanero
----

- List the appsody stacks available in the Collection:

[source, bash]
----
appsody list kabanero
----

It gives you the list of available stacks.

[source, bash]
----
$ appsody list kabanero

REPO    	ID               	VERSION  	TEMPLATES        	DESCRIPTION
kabanero	java-microprofile	0.2.11   	*default         	Eclipse MicroProfile on Open Liberty & OpenJ9 using Maven
kabanero	java-spring-boot2	0.3.9    	*default, kotlin 	Spring Boot using OpenJ9 and Maven
kabanero	nodejs           	0.2.5    	*simple          	Runtime for Node.js applications
kabanero	nodejs-express   	0.2.5    	*simple, skaffold	Express web framework for Node.js
kabanero	nodejs-loopback  	0.1.4    	*scaffold        	LoopBack 4 API Framework for Node.js
----

== Create a new Application using appsody

- Create a new directory for the project and change directory into it.

[source, bash]
----
mkdir appsody_sample_springboot
cd appsody_sample_springboot/
----

- Initialize the project using `appsody init` and select the desired stack ID.

[source, bash]
----
appsody init kabanero/java-spring-boot2
----

- Extract the appsody deployment config.

[source, bash]
----
appsody deploy --generate-only
----

This will generate you the below file.

[source, yaml]
----
apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  name: appsody-sample-springboot
spec:
  # Add fields here
  version: 1.0.0
  applicationImage: appsody-sample-springboot
  stack: java-spring-boot2
  service:
    type: NodePort
    port: 8080
    annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path: '/actuator/prometheus'
  readinessProbe:
    failureThreshold: 12
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 2
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /actuator/liveness
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 2
  expose: true
----

By default, the application is deployed in the `kabanero` namespace. If you want to deploy the application in a different namespace, you can specify it in this yaml file. In this lab, let us use a namespace called `kabanero-samples-java` and we can specify it under the metadata as below.

[source, yaml]
----
apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  name: appsody-sample-springboot
  namespace: kabanero-samples-java
spec:
  # Add fields here
  version: 1.0.0
  applicationImage: appsody-sample-springboot
  stack: java-spring-boot2
  service:
    type: NodePort
    port: 8080
    annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path: '/actuator/prometheus'
  readinessProbe:
    failureThreshold: 12
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 2
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /actuator/liveness
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 2
  expose: true
----

== Run the Application using Appsody

- Run the application using appsody

[source, bash]
----
appsody run
----

This step is building a container and running it, the output has the endpoint for the application.

----
Running development environment...
Running command: docker[pull kabanero/java-spring-boot2:0.3]
Running docker command: docker[run --rm -p 5005:5005 -p 8080:8080 -p 35729:35729 --name appsody-sample-springboot-dev -u 501:20 -e APPSODY_USER=501 -e APPSODY_GROUP=20 -v /Users/<user>@ibm.com/kabanero101/appsody_sample_springboot/.:/project/user-app -v /Users/<user>@ibm.com/.m2/repository:/mvn/repository -v /Users/<user>@ibm.com/.appsody/appsody-controller:/appsody/appsody-controller -t --entrypoint /appsody/appsody-controller kabanero/java-spring-boot2:0.3 --mode=run]
......
......
......
[Container] 2019-09-12 17:49:22.173  INFO 185 --- [  restartedMain] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 4 endpoint(s) beneath base path '/actuator'
[Container] 2019-09-12 17:49:22.377  INFO 185 --- [  restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
[Container] 2019-09-12 17:49:22.386  INFO 185 --- [  restartedMain] application.Main                         : Started Main in 7.984 seconds (JVM running for 9.679)
[Container] 2019-09-12 17:58:42.777  INFO 185 --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
[Container] 2019-09-12 17:58:42.777  INFO 185 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
[Container] 2019-09-12 17:58:42.805  INFO 185 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 27 ms
[Container] 2019-09-12 17:58:43.044  INFO 185 --- [nio-8080-exec-1] i.j.internal.reporters.LoggingReporter   : Span reported: 445d02b19cea491:445d02b19cea491:0:1 - GET
----

- Open the application using the web browser at http://localhost:8080.

== Stop the Application using Appsody

- To stop the container, run this command.

[source, bash]
----
appsody stop
----

- Alternatively, you can also press `Ctrl+C`.

== Debug the Application using Appsody

To debug the application including reloading the application on code changes run the below command.

[source, bash]
----
appsody debug
----

The output indicates the debug environment is being used

[source, bash]
----
$ appsody debug
Running debug environment
Running command: docker[pull kabanero/java-spring-boot2:0.3]
Running docker command: docker[run --rm -p 35729:35729 -p 5005:5005 -p 8080:8080 --name appsody-sample-springboot-dev -u 501:20 -e APPSODY_USER=501 -e APPSODY_GROUP=20 -v /Users/<user>@ibm.com/kabanero101/appsody_sample_springboot/.:/project/user-app -v /Users/<user>@ibm.com/.m2/repository:/mvn/repository -v /Users/<user>@ibm.com/.appsody/appsody-controller:/appsody/appsody-controller -t --entrypoint /appsody/appsody-controller kabanero/java-spring-boot2:0.3 --mode=debug]
.......
.......
.......
[Container] [INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ application ---
[Container] [INFO] Changes detected - recompiling the module!
[Container] [INFO] Compiling 1 source file to /project/user-app/target/test-classes
[Container] [INFO]
[Container] [INFO] <<< spring-boot-maven-plugin:2.1.6.RELEASE:run (default-cli) < test-compile @ application <<<
[Container] [INFO]
[Container] [INFO]
[Container] [INFO] --- spring-boot-maven-plugin:2.1.6.RELEASE:run (default-cli) @ application ---
[Container] [INFO] Attaching agents: []
[Container] Listening for transport dt_socket at address: 5005
----

You can make changes to the application for example changing the title in `index.html`. You can access it at `src/main/resources/public/index.html`.

The change will be detected and the application will be restarted inside the running container.
