= SpringBoot - Appsody sample application
Hemankita Perabathini <Hemankita.Perabathini@ibm.com>
v1.0, 2019-09-17
:toc:
:imagesdir: images

== Prerequisites

* https://cloud.ibm.com/kubernetes/catalog/openshiftcluster[Openshift] (We are using the IKS Openshift cluster)
* Docker for Desktop - https://docs.docker.com/docker-for-mac/install/[Mac], https://docs.docker.com/docker-for-windows/install/[Windows]
* The following command line (CLI) tools and configured:
  ** docker - It comes with the Docker for Desktop installation.
  ** https://www.okd.io/download.html[oc]
  ** https://git-scm.com/book/en/v2/Getting-Started-Installing-Git[git]
  ** https://appsody.dev/docs/getting-started/installation[appsody]

== Add Kabanero Collection to appsody

- From the Cloud Pak for Applications landing page get the `Collection Hub` URL. For example in our example it is as follows.

`https://github.com/kabanero-io/collections/releases/download/v0.1.2/kabanero-index.yaml`

- Use the appsody CLI to add the Collection repo.

[source, bash]
----
appsody repo add kabanero https://github.com/kabanero-io/collections/releases/download/v0.1.2/kabanero-index.yaml
----

- Set the repo as default.

[source, bash]
----
appsody repo set-default kabanero
----

- List the appsody stacks available in the Collection:

[source, bash]
----
appsody list kabanero
----

It gives you the list of available stacks.

[source, bash]
----
$ appsody list kabanero

REPO    	ID               	VERSION  	TEMPLATES        	DESCRIPTION
kabanero	java-microprofile	0.2.11   	*default         	Eclipse MicroProfile on Open Liberty & OpenJ9 using Maven
kabanero	java-spring-boot2	0.3.9    	*default, kotlin 	Spring Boot using OpenJ9 and Maven
kabanero	nodejs           	0.2.5    	*simple          	Runtime for Node.js applications
kabanero	nodejs-express   	0.2.5    	*simple, skaffold	Express web framework for Node.js
kabanero	nodejs-loopback  	0.1.4    	*scaffold        	LoopBack 4 API Framework for Node.js
----

== Create a new Application using appsody

- Create a new directory for the project and change directory into it.

[source, bash]
----
mkdir appsody_sample_springboot
cd appsody_sample_springboot/
----

- Initialize the project using `appsody init` and select the desired stack ID.

[source, bash]
----
appsody init kabanero/java-spring-boot2
----

- Extract the appsody deployment config.

[source, bash]
----
appsody deploy --generate-only
----

This will generate you the below file.

[source, yaml]
----
apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  name: appsody-sample-springboot
spec:
  # Add fields here
  version: 1.0.0
  applicationImage: appsody-sample-springboot
  stack: java-spring-boot2
  service:
    type: NodePort
    port: 8080
    annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path: '/actuator/prometheus'
  readinessProbe:
    failureThreshold: 12
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 2
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /actuator/liveness
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 2
  expose: true
----

By default, the application is deployed in the `kabanero` namespace. If you want to deploy the application in a different namespace, you can specify it in this yaml file. In this lab, let us use a namespace called `kabanero-samples-java` and we can specify it under the metadata as below.

[source, yaml]
----
apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  name: appsody-sample-springboot
  namespace: kabanero-samples-java
spec:
  # Add fields here
  version: 1.0.0
  applicationImage: appsody-sample-springboot
  stack: java-spring-boot2
  service:
    type: NodePort
    port: 8080
    annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path: '/actuator/prometheus'
  readinessProbe:
    failureThreshold: 12
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 2
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /actuator/liveness
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 2
  expose: true
----
