= Appsody - Create a Stack
Bryan Kribbs <bakribbs@us.ibm.com>
v1.0, 2019-09-24
:toc:

== Prerequisites

* https://cloud.ibm.com/kubernetes/catalog/openshiftcluster[Openshift Cluster]
** Install Appsody Operator that watches on all namespaces https://github.com/appsody/appsody-operator/tree/master/deploy/releases/0.1.0
* Docker for Desktop - https://docs.docker.com/docker-for-mac/install/[Mac], https://docs.docker.com/docker-for-windows/install/[Windows]
* The following command line (CLI) tools and configured:
** docker - It comes with the Docker for Desktop installation.
** https://www.okd.io/download.html[oc]
** https://git-scm.com/book/en/v2/Getting-Started-Installing-Git[git]
** https://appsody.dev/docs/getting-started/installation[appsody]

== Getting Started

First we need to clone the stacks repository provided by appsody.

----
git clone https://github.com/appsody/stacks.git
cd stacks/samples/sample-stack
----

The stacks repository provides us with the basic structure for a stack.

== Stack Structure

The structure of a stack repository is relative simple.  There is a `image` directory which holds everything that is needed for the stack's image to run. A `templates` directory which contains the different templates for the stack and each template has it's own directory. Finally there is a `README.md` and `stack.yaml` file in the parent directory. The `README.md` is for basic information about the stack and the `stack.yaml` provides information to appsody about the stack.

### Appsody Stack Directory Layout

    .
    ├── /image                
        ├── /config           
        ├── /project
            ├── /test            
        ├── dockerfile-stack   
        ├── LICENSE
    ├── /templates            
        ├── <Name of Template 1> 
        ├── <Name of Template 2> 
    ├── Stack.yaml
    └── README.md


