apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: java-spring-boot2-test-build-deploy-pipeline
spec:
  resources:
    - name: git-source
      type: git
    - name: docker-image
      type: image
  tasks:
    - name: test-task
      taskRef:
        name: java-spring-boot2-test-task
      resources:
        inputs:
          - name: git-source
            resource: git-source
    - name: build-task
      taskRef:
        name: java-spring-boot2-build-task
      runAfter: [test-task]
      resources:
        inputs:
          - name: git-source
            resource: git-source
        outputs:
          - name: docker-image
            resource: docker-image
    - name: deploy-task
      taskRef:
        name: java-spring-boot2-deploy-task
      runAfter: [build-task]
      resources:
        inputs:
          - name: git-source
            resource: git-source
          - name: docker-image
            resource: docker-image
